# Generated by Django 2.0.7 on 2018-08-31 21:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha Reporte de caso')),
                ('genero', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=1)),
                ('edad', models.SmallIntegerField(verbose_name='Edad')),
                ('finalidadExplotación', models.CharField(choices=[('ex', 'Explotación de la prostitución ajena u otras formas de Explotación sexual'), ('tr', 'Trabajos o servicios forzosos'), ('me', 'Mendicidad ajena'), ('ma', 'Matrimonio servil'), ('or', 'Extracción de órganos'), ('es', 'Practicas análogas a la esclavitud'), ('se', 'Servidumbre'), ('ot', 'Otro')], max_length=2, verbose_name='Finalidad de explotación')),
                ('estratoSocioeconomico', models.SmallIntegerField(default=0, verbose_name='Estrato socioeconómico')),
                ('medioContacto', models.CharField(choices=[('re', 'Redes sociales'), ('cl', 'Clasificados'), ('ra', 'Radio'), ('am', 'Amigo'), ('pr', 'Pareja'), ('ot', 'Otro')], max_length=2, verbose_name='Medio de contacto')),
                ('formaCaptación', models.CharField(choices=[('ol', 'Oferta laboral'), ('re', 'Relación sentimental'), ('oa', 'Oferta académica'), ('tu', 'Turismo'), ('ot', 'Otro')], max_length=2, verbose_name='Medio de contacto')),
                ('tipoTrata', models.CharField(choices=[('i', 'Interna'), ('e', 'Externa')], max_length=1)),
                ('descriptFormaCap', ckeditor.fields.RichTextField(verbose_name='Descripción de la forma de captación')),
                ('lugarExplotación', models.CharField(max_length=200, verbose_name='Lugar')),
                ('medioTransporte', models.CharField(choices=[('i', 'Interna'), ('e', 'Externa')], max_length=1)),
                ('rutaTraslado', models.CharField(max_length=200, verbose_name='Ruta de traslado de la presunta víctima')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
