# Generated by Django 2.0.7 on 2018-08-31 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='lugarExplotación',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Ciudad'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='medioTransporte',
            field=models.CharField(choices=[('a', 'Avión'), ('b', 'Bus'), ('m', 'Maritimo'), ('o', 'Otro')], max_length=1, verbose_name='Medio de transporte utilizado'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='tipoTrata',
            field=models.CharField(choices=[('i', 'Interna'), ('e', 'Externa')], max_length=1, verbose_name='Tipo de trata'),
        ),
    ]
