# Generated by Django 2.0.7 on 2018-08-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180831_1533'),
        ('core', '0002_auto_20180831_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='formaCaptación',
            field=models.CharField(choices=[('ol', 'Oferta laboral'), ('re', 'Relación sentimental'), ('oa', 'Oferta académica'), ('tu', 'Turismo'), ('ot', 'Otro')], max_length=2, verbose_name='Forma de captación'),
        ),
        migrations.RemoveField(
            model_name='caso',
            name='lugarExplotación',
        ),
        migrations.AddField(
            model_name='caso',
            name='lugarExplotación',
            field=models.ManyToManyField(related_name='get_ciudades', to='registration.Ciudad'),
        ),
    ]
