# Generated by Django 2.0.7 on 2018-09-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180831_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.SmallIntegerField(verbose_name='Edad')),
                ('lugarOrigen', models.TextField(verbose_name='Lugar de origen')),
                ('estratoSocioeconomico', models.SmallIntegerField(default=0, verbose_name='Estrato socioeconómico')),
                ('lugarDestino', models.TextField(verbose_name='Lugar de destino')),
                ('motivoViaje', models.CharField(choices=[('l', 'Oferta laboral'), ('t', 'Turismo'), ('a', 'Oferta academica'), ('s', 'Relación sentimental')], max_length=1, verbose_name='Motivo del viaje')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', models.TextField(blank=None, null=None, verbose_name='Descripción de la forma de captación')),
                ('motivo', models.CharField(choices=[('l', 'Oferta laboral'), ('t', 'Turismo'), ('a', 'Oferta academica'), ('s', 'Relación sentimental')], max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
