# Generated by Django 2.0.7 on 2018-09-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfilpersona_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpersona',
            name='dni',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilpersona',
            name='nombreCompleto',
            field=models.CharField(default=123, max_length=200, verbose_name='Nombre completo'),
            preserve_default=False,
        ),
    ]
