# Generated by Django 2.0.7 on 2018-08-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180717_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typeProfile',
            field=models.CharField(blank=True, choices=[('o', 'Operario'), ('e', 'Entidad')], max_length=1),
        ),
    ]
