# Generated by Django 2.0.7 on 2018-08-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180831_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dni',
            field=models.PositiveIntegerField(default=123),
            preserve_default=False,
        ),
    ]
