# Generated by Django 2.0.7 on 2018-08-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_profile_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dni',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
